{% set name = "pytest-reraise" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-reraise-{{ version }}.tar.gz
  sha256: 5ab59bd0e2028be095289e6dfc9e36cc0b56936465278f3223e81bea0f2d1c70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=4.6

test:
  imports:
    - pytest_reraise
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bjoluc/pytest-reraise
  summary: Make multi-threaded pytest test cases fail when they should
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - nicornk
